@echo off
set PATH=C:\BIN;C:\WINDOWS;C:\DOS
set LIB=C:\LIB;C:\INCLUDE;C:\DDK\286\LIB
set INCLUDE=C:\INCLUDE;C:\DDK\286\INC
masm ADDNUM.ASM,ADDNUM.OBJ,,; > MASM.TXT
cl /nologo /c /FoHELLOWOR.OBJ HELLOWOR.C > COMPILER.TXT
echo. | link HELLOWOR.OBJ ADDNUM.OBJ,HELLOWOR.EXE,,; > LINKER.TXT
